pr: none
trigger: none

pool:
  vmImage: 'vs2017-win2016'

variables:
 - name: BuildingInVsts
   value: true
 - name: SolutionDirectory 
   value: 'src\FiscalIntegration\Efr'

steps:
  - task: PowerShell@2
    displayName: 'Pre-Build steps'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowershellScripts/Pre-Build.ps1
      failOnStderr: true

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.4.0'
    inputs:
      versionSpec: '5.4.0'

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      feedsToUse: config
      nugetConfigPath: nuget.config

  - task: VSBuild@1
    displayName: 'Build solution EFR.sln'
    inputs:
      solution: '$(Build.SourcesDirectory)\$(SolutionDirectory)\EFR.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Install AzureSignTool'
    inputs:
      command: custom
      custom: tool
      arguments: 'install --global azuresigntool'

  - task: PowerShell@2
    displayName: 'Copy CloudScaleUnitExtensionPackage package to artifact directory'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowershellScripts/CopyFileToDestination.ps1
      arguments: '-RelativePath "$(Build.SourcesDirectory)\$(SolutionDirectory)\ScaleUnit\ScaleUnit.EFR" -File "CloudScaleUnitExtensionPackage.zip" -DestinationFullName "$(Build.ArtifactStagingDirectory)\ScaleUnitPackage_$(Build.BuildNumber).zip"'

  - task: PowerShell@2
    displayName: 'Copy Hardware Station Installer to Artifact directory'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowerShellScripts/CopyFileToDestination.ps1
      arguments: '-RelativePath "$(Build.SourcesDirectory)\$(SolutionDirectory)\HardwareStation\HardwareStation.EFR.Installer" -File "HardwareStation.EFR.Installer.exe" -DestinationFullName "$(Build.ArtifactStagingDirectory)\HardwareStation.EFR.Installer_$(Build.BuildNumber).exe"'

  - task: PowerShell@2
    displayName: 'Copy Scale Unit Installer to Artifact directory'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowerShellScripts/CopyFileToDestination.ps1
      arguments: '-RelativePath "$(Build.SourcesDirectory)\$(SolutionDirectory)\ScaleUnit\ScaleUnit.EFR.Installer" -File "ScaleUnit.EFR.Installer.exe" -DestinationFullName "$(Build.ArtifactStagingDirectory)\ScaleUnit.EFR.Installer_$(Build.BuildNumber).exe"'

  - task: PowerShell@2
    displayName: 'Copy Modern POS Installer to Artifact directory'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowerShellScripts/CopyFileToDestination.ps1
      arguments: '-RelativePath "$(Build.SourcesDirectory)\$(SolutionDirectory)\ModernPos\ModernPos.EFR.Installer" -File "ModernPos.EFR.Installer.exe" -DestinationFullName "$(Build.ArtifactStagingDirectory)\ModernPos.EFR.Installer_$(Build.BuildNumber).exe"'

  - task: PowerShell@2
    displayName: 'Sign Files'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowerShellScripts/CodeSign.ps1
      arguments: '-AzureKeyVaultURI $(AzureKeyVaultURI) -ApplicationId $(ApplicationId) -ApplicationSecretValue $(SecretValue) -CertificateName $(CertificateName) -Timestamp $(Timestamp) -TimestampDigest "sha256" -Files "$(Build.ArtifactStagingDirectory)\HardwareStation.EFR.Installer_$(Build.BuildNumber).exe $(Build.ArtifactStagingDirectory)\ScaleUnit.EFR.Installer_$(Build.BuildNumber).exe $(Build.ArtifactStagingDirectory)\ModernPos.EFR.Installer_$(Build.BuildNumber).exe"'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'